version: "3.8"

# services daftar container yang akan dibuat docker-compose
# key nya boleh apa saja tetapi unique
services:
  nginx-port1:
    image: nginx:latest
    container_name: nginx-port1
    # long syntax, protocol (tcp atau udp), published (port host), target(port deamon/container)
    ports:
      - protocol: tcp
        published: 8080
        target: 80
    # Resource Limit
    #  mengatur Resource Limit untuk CPU dan Memory dari tiap Container yang akan kita buat
    # attribute deploy, lalu didalamnya menggunakan attribute resources
    # attribute reservation adalah resource yang dijamin bisa digunakan oleh container
    # ini sangat riskan karna limit ini bisa rebutan dengan container yang lain
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 50M
        limits:
          cpus: "0.5"
          memory: 100M