version: "3.9"

# services daftar container yang akan dibuat docker-compose
# key nya boleh apa saja tetapi unique
services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    # short syntax, string port HOST:CONTAINER
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: budhi
      MONGO_INITDB_ROOT_PASSWORD: budhi
      MONGO_INITDB_DATABASE: admin
    # mengunakan networks yang sudah dibuat, tingal ambil key nyaa
    networks:
      - network_example

# networks di buat manual,
# name: nama
# network, driver: bridge(host dan deamon/container terhubung), host(hanya host), dan none(keduanya tidak terhubung)
networks:
  network_example:
    name: network_example
    driver: bridge